# Generated by Django 5.2.5 on 2025-10-23 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMapControl', '0002_auto_20251023_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Stock', 'Stock'), ('Mutual Fund', 'Mutual Fund'), ('Crypto', 'Crypto'), ('Other', 'Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
